export const SET_ACCEPTED = 'SET_ACCEPTED'

export const SET_FAIL = 'SET-FAIL'

export const RESET_STATE = 'RESET_STATE'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_COMPANY_LIST = 'SET_COMPANY_LIST'

export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY'

export const SET_PURCHASE_ORDER_LIST = 'SET_PURCHASE_ORDER_LIST'

export const SET_USER = 'SET_USER'

/* export const SET_CREATE_CART = 'SET_CREATE_CART'

export const SET_CART_COUNTER = 'SET_CART_COUNTER'

export const SET_ORDERS = 'SET_ORDERS'

export const SET_ORDER_CARTS = 'SET_ORDER_CARTS'

export const SET_EMPLOYEE_CARTS = 'SET_EMPLOYEE_CARTS'

export const RESET_USER = 'RESET_USER'

export const SET_CART_ID = 'SET_CART_ID' */