//Redux action types for reducers

export const SET_ACCEPTED = 'SET_ACCEPTED'

export const SET_FAIL = 'SET-FAIL'

export const RESET_STATE = 'RESET_STATE'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_COMPANY_LIST = 'SET_COMPANY_LIST'

export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY'

export const SET_READ_PURCHASE_ORDER_LIST = 'SET_READ_PURCHASE_ORDER_LIST'

export const SET_READ_RECEIVE_INVENTORY_LIST = 'SET_READ_RECEIVE_INVENTORY_LIST'

export const SET_READ_PAY_BILLS_LIST = 'SET_READ_PAY_BILLS_LIST'

export const SET_USER = 'SET_USER'